name: Release
on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn --cwd package install --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
          yarn --cwd package lint
      - name: Test
        run: yarn test
      - name: Build project
        run: yarn package:update
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd package
          npx semantic-release
